canonical: https://gematik.de/fhir/epa-medication
fhirVersion: 4.0.1
dependencies:
  de.gematik.erezept-workflow.r4: 1.2.2
  de.basisprofil.r4: 1.3.2
  de.gematik.fhir.directory: 0.10.2
  kbv.ita.erp: 1.1.2   
FSHOnly: true