canonical: https://gematik.de/fhir/epa-medication
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.4.0
  de.gematik.fhir.directory: 0.10.2
  de.gematik.erezept-workflow.r4: 1.2.3
  kbv.ita.erp: 1.1.2   
FSHOnly: true