Profile: RxPrescriptionProcessIdentifier
Parent: Identifier
Id: rx-prescription-process-identifier
Description: "This transaction identifier is used to track medication prescription transactions between the E-Rezept-Fachdienst and the ePA. It is generated by the ePA Medication Service, ensuring a consistent and unique identification of each transaction. The identifier is composed of the PrescriptionId and the authoredOn-date of the operations parameters request, providing a robust mechanism for referencing and managing medication-related resources across systems."
* insert Meta
* system 1..1 MS
* system = "https://gematik.de/fhir/epa-medication/sid/rx-prescription-process-identifier"
* value 1.. MS
