@startuml concept.operation.link-prescription-process.in.erp.op
skinparam defaultTextAlignment center
skinparam title {
  backgroundColor SkyBlue
  borderColor Gray
} 
' title Bearbeitung ausstehender Tasks durch die Operation $provide-prescription-erp

start
    :Empfang der Verschreibungsdaten;

    if(\nExistiert eine nicht abgeschlossene <b>Task</b>-Ressource für die Verschreibungsdaten?\n) then (JA)
        :Durchführung der Verlinkung;
        :Die <b>Task</b>-Ressource wird vollständig vom Medication Service entfernt (<b>Hard Delete</b>).;
    else (NEIN)
    endif
  
stop
@enduml
