@startuml concept.operation.link-prescription-process
skinparam defaultTextAlignment center
skinparam title {
  backgroundColor SkyBlue
  borderColor Gray
} 
' title Initiierung der Verlinkung über $link-prescription-process

start
    :<b>Initiierung der Verlinkung</b>;

    if(\nSind die relevanten Verschreibungsdaten bereits\ndurch den E-Rezept-Fachdienst übermittelt worden?\n) then (Verschreibungsdaten verfügbar)
        :Verschreibungsdaten werden sofort verlinkt;
    else (Verschreibungsdaten nicht verfügbar)
        :Eine <b>Task</b>-Ressource wird erstellt\nund ihr Status auf <b>requested</b> gesetzt.;
    endif
  
stop
@enduml
