@startuml

skinparam Shadowing false
skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    ArrowColor DodgerBlue
    ActorBorderColor DodgerBlue
    LifeLineBorderColor Blue

    ParticipantBackgroundColor #3483eb
    ParticipantBorderColor #3483eb
    ParticipantFontSize 14
    ParticipantFontColor White

    ActorBackgroundColor #3483eb
    ActorFontSize 14
    NoteBackgroundColor #3483eb
}

hide footbox
autonumber

participant "AVS" as PVS
participant "E-Rezept-Fachdienst" as ERFD

box "ePA-Aktensystem" #LightGray
    participant "Information Service" as IS
end box

box "ePA-Aktensystem / VAU" #Beige
    participant "VAU \nSession \nManagement" as VAU #eb5e34
    participant "Medication Service" as EPA
end box

PVS -> ERFD: Anfrage: Dispensierinformationen löschen
ERFD -> ERFD: Durchführen der standardisierten Workflow-Logik des E-Rezept-Fachdienstes
ERFD --> PVS: Antwort: Erfolg

ERFD -> ERFD: Persistieren der Resource ID der zu stornierenden Dispensierinformationen (aus MedicationDispense)\nin einer Warteschlange für die asynchrone Übertragung

ref over ERFD, IS: Lokalisierung der Service-Endpunkte der ePA und der Akte eines Versicherten

ERFD -> IS: Anfrage: Widerspruchsinformationen zum Einstellen durch E-Rezept-Fachdienst
IS --> ERFD: Antwort: Widerspruchsinformationen

alt Widerspruch zum Einstellen durch E-Rezept-Fachdienst vorhanden
    ERFD -> ERFD: Abbruch. Löschen der Resource ID der zu stornierenden Dispensierinformationen aus der Warteschlange
else Kein Widerspruch zum Einstellen durch E-Rezept-Fachdienst

    ref over ERFD, VAU: Login in die Akte des Versicherten

    ERFD -> EPA: Übermittlung des rxPrescriptionProcessIdentifier in der FHIR Operation per HTTP POST
    EPA -> EPA: MedicationDispense.status = "cancelled"\naktualisieren

    alt successful case
        EPA --> ERFD: Antwort: Transaktion erfolgreich
        ERFD -> ERFD: Löschen der Resource ID der zu stornierenden Dispensierinformationen aus der Warteschlange
    else
        ERFD -> ERFD: Abbruch. Die Resource ID der zu stornierenden Dispensierinformationen bleibt in der Warteschlange\nfür eine spätere Übertragung
    end

end

@enduml