@startuml

skinparam Shadowing false
skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    ArrowColor DodgerBlue
    ActorBorderColor DodgerBlue
    LifeLineBorderColor Blue

    ParticipantBackgroundColor #3483eb
    ParticipantBorderColor #3483eb
    ParticipantFontSize 14
    ParticipantFontColor White

    ActorBackgroundColor #3483eb
    ActorFontSize 14
    NoteBackgroundColor #3483eb
}

hide footbox
autonumber

participant "PVS/KIS" as PVS
participant "E-Rezept-Fachdienst" as ERFD

box "ePA-Aktensystem" #LightGray
    participant "Information Service" as IS
end box

box "ePA-Aktensystem / VAU" #Beige
    participant "VAU \nSession \nManagement" as VAU #eb5e34
    participant "Medication Service" as EPA
end box

PVS -> ERFD: Anfrage: Verordnungsdatensatz löschen
ERFD -> ERFD: Durchführen der standardisierten Workflow-Logik des E-Rezept-Fachdienstes
ERFD --> PVS: Antwort: Erfolg

ERFD -> ERFD: Persistieren der Resource ID des zu stornierenden Verordnungsdatensatzes (aus MedicationRequest)\nin einer Warteschlange für die asynchrone Übertragung

ref over ERFD, IS: Lokalisierung der Service-Endpunkte der ePA und der Akte eines Versicherten (s. Abschn. 4.1, 4.2)

ERFD -> IS: Anfrage: Widerspruchsinformationen zu Versorgungsprozessen
IS --> ERFD: Antwort: Widerspruchsinformationen

alt Widerspruch zum Versorgungsprozess dgMP vorhanden
    ERFD -> ERFD: Abbruch. Löschen der Resource ID des zu stornierenden Verordnungsdatensatzes aus der Warteschlange
else Kein Widerspruch zum Versorgungsprozess dgMP

    ref over ERFD, VAU: Login in die Akte des Versicherten (siehe. Abschn. 4.3)

    ERFD -> EPA: Übermittlung des rxPrescriptionProcessIdentifier in der FHIR Operation per HTTP POST
    EPA -> EPA: MedicationRequest.status = "cancelled"\naktualisieren

    alt successful case
        EPA --> ERFD: Antwort: Transaktion erfolgreich
        ERFD -> ERFD: Löschen der Resource ID des zu stornierenden Verordnungsdatensatzes aus der Warteschlange
    else
        ERFD -> ERFD: Abbruch. Die Resource ID des zu stornierenden Verordnungsdatensatzes bleibt in der Warteschlange\nfür eine spätere Übertragung
    end

end

@enduml