@startuml medication.fhir.substitution
skinparam fixCircleLabelOverlapping false 
skinparam roundcorner 10
skinparam object {
    BackgroundColor DimGrey
    BorderColor Black
    ArrowColor #5c7aab
    FontSize 12
    FontColor White
    NoteBackgroundColor #3483eb
    ArrowFontColor #777777
}
skinparam LegendBackgroundColor White

object "<< Versicherter >>\n**Patient**" as Patient 
object "<< Verschreibender LE >>\n**PractitionerDirectory**" as PrescribingPractitioner
object "<< Verschreibende LEI >>\n**OrganizationDirectory**" as PrescribingOrganization
object "<< Abgebende LEI >>\n**OrganizationDirectory**" as PharmOrganization
object "PractitionerRole" as PractionerRole
object "<< Arzneimittel >>\n**EPAMedication**" as Medication #DarkSeaGreen
object "<< Arzneimittelverschreibung >>\n**EPAMedicationRequest**" as MedicationRequest #DarkSeaGreen {
    + subject: Reference(Patient)
}
object "<< Substituiertes Arzneimittel >>\n**EPAMedication**" as AltMedication #DarkSeaGreen
object "<< Dispensierinformation >>\n**EPAMedicationDispense**" as MedicationDispense #DarkSeaGreen {
    + wasSubstituted: true
}

MedicationRequest -d->  Patient : subject
MedicationRequest -l-> Medication : medicationReference
MedicationRequest -r-> PractionerRole : requester

PractionerRole -d-> PrescribingPractitioner : practitioner
PractionerRole -d-> PrescribingOrganization : organization

MedicationDispense -l-> AltMedication : medicationReference
MedicationDispense -d-> MedicationRequest : authorizingPrescription
MedicationDispense -u-> PharmOrganization : perfomer.actor

legend left
    | Color | Data |
    |<#DarkSeaGreen>| Prescription Data |
    |<#DimGrey>| Actors |
endlegend
@enduml
