@startuml medication.fhir.model
skinparam fixCircleLabelOverlapping false
skinparam roundcorner 10
skinparam object {
    BackgroundColor DimGrey
    BorderColor Black
    ArrowColor #5c7aab
    FontSize 12
    FontColor White
    NoteBackgroundColor #3483eb
    ArrowFontColor #777777
}
skinparam LegendBackgroundColor White

object "<< Versicherter >>\n**EPAPatient**" as Patient 
object "<< Verschreibender LE >>\n**PractitionerDirectory**" as PrescribingPractitioner
object "<< Verschreibende LEI >>\n**OrganizationDirectory**" as PrescribingOrganization
object "<< Abgebende LEI >>\n**OrganizationDirectory**" as DispenserOrganization
object "EPAPractitionerRole" as PractionerRole
object "<< Arzneimittel >>\n**EPAMedication**" as Medication #DarkSeaGreen 
object "<< Arzneimittelverschreibung >>\n**EPAMedicationRequest**" as MedicationRequest #DarkSeaGreen  {
    + subject: Reference(EPAPatient)
}
object "<< Dispensierung >>\n**EPAMedicationDispense**" as MedicationDispense #DarkSeaGreen 


MedicationRequest -u->  Patient : subject
MedicationRequest -r-> Medication : medicationReference
MedicationRequest -d-> PractionerRole : requester

PractionerRole -u-> PrescribingPractitioner : practitioner
PractionerRole -d-> PrescribingOrganization : organization

MedicationDispense -u-> Medication : medicationReference
MedicationDispense -l-> MedicationRequest : authorizingPrescription
MedicationDispense -d-> DispenserOrganization : perfomer.actor


legend right
    | Color | Data |
    |<#DarkSeaGreen>| Prescription Data |
    |<#DimGrey>| Actor |
endlegend
@enduml