@startuml operation.cancel-dispensation-erp
skinparam defaultTextAlignment center
<style>
title {
  backgroundColor SkyBlue
  borderColor Gray
}
activityDiagram {
  diamond {
    BackgroundColor #Business
  }
}
.iDTokenCheck {

}
legend {
  backgroundColor White
}
</style>
title $cancel-dispensation-erp

start


  repeat:Get next <b>RxDispensation</b> from the <b>Input-Parameters</b>;

    :Generate <b>RxPrescriptionProcessIdentifier</b> from the values of
    <b>Input-Parameters</b>[x].<b>RxDispensation</b>.part.<b>authoredOn</b> and the
    <b>Input-Parameters</b>[x].<b>RxDispensation</b>.part.<b>PrescriptionId</b>;
    note right

      The generation of the value for
      the **RxPrescriptionProcessIdentifier**
      is described below the diagram.

    end note

    if(\rCheck whether there is at least one <b>MedicationDispense </b> with the <b>RxPrescriptionProcessIdentifier</b> already in the Medication Service\r) then (yes)

      partition transaction {

        :Set all <b>MedicationDispense</b> with the
        extension[RxPrescriptionProcessIdentifier] equal to <b>RxPrescriptionProcessIdentifier</b>
        to Status <b>cancelled</b>;

        :Set all <b>Medication</b> with the
        extension[RxPrescriptionProcessIdentifier] equal to <b>RxPrescriptionProcessIdentifier</b>
        to Status <b>inactive</b>;

        :Set <b>MedicationRequest</b> with the
        identifier[RxPrescriptionProcessIdentifier] equal to <b>RxPrescriptionProcessIdentifier</b>
        to Status <b>active</b>;

        #PaleGreen:Add information **OperationOutcome**
        with details MEDICATIONSVC_OPERATION_SUCCESS
        to the **Output-Parameters**;

      }

    else (no)

      #Pink:Add error <b>OperationOutcome</b>
      with details MEDICATIONSVC_DISPENSATION_NO_EXIST or MEDICATIONSVC_DISPENSATION_STATUS
      to the <b>Output-Parameters</b>;

    endif

  repeat while (If next <b>Input-Parameters</b> exists) is (yes) not (no)

#PaleGreen:Return <b>Output-Parameters</b>;
stop
legend right
    | Color | Activity type |
    |<#PaleGreen>| Successful output |
    |<#Pink>| Error output |
    |<#Business>| Conditions |

endlegend
@enduml
